### ISSUE TITLE
Looks cool!

### ISSUE THREAD

**Issue by fakefarm** [rudism/dropbox-music-player#6]
Hey @rudism, 

Just came across this and looking forward to trying it out.

Personally, I'm sitting on 13k songs in DB and getting tired of moving them from laptop to laptop. Of course most of these tracks are not on spotify and even if they were, I can't justify spending $10 mo for music I already own.

Thanks for building this and I'll keep you posted!

**Comment by rudism** [comment]
Thanks for the feedback, I hope it works out for you. I've only got about 5k songs myself, split across around 340 albums or so.
